import Head from 'next/head'
import { Footer } from '../components/Footer'
import styles from '../styles/Home.module.css'
import { Main } from '../components/Main'
import { Header } from '../components/Header'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Main page="index" />

      <Footer />
    </div>
  )
}
